# Generated by Django 5.0.6 on 2024-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serving_size_g', models.FloatField()),
                ('calories', models.FloatField()),
                ('carbohydrates_total_g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('fat_total_g', models.FloatField()),
                ('sugar_g', models.FloatField()),
                ('fiber_g', models.FloatField()),
                ('sodium_mg', models.FloatField()),
                ('potassium_mg', models.FloatField()),
                ('fat_saturated_g', models.FloatField()),
                ('cholesterol_mg', models.FloatField()),
            ],
        ),
    ]
